### ISSUE TITLE
3.1.0 is missing from PyPI and tags

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.ZopeVersionControl#12]
@dataflake: you prepared a 3.1.0 release in December, but it is not on PyPI and not in the tags on GitHub. I guess something went wrong there. Can you try again please?

**Comment by dataflake** [comment]
The tag is now set but I do not have rights for the PyPI page.

**Comment by mauritsvanrees** [comment]
Ah, I see I have PyPI rights myself, via the plone account. Thanks for pushing the tag, now I can release it. Done:
https://pypi.org/project/Products.ZopeVersionControl/3.1.0/

Shall I give you PyPI rights?

**Comment by dataflake** [comment]
Yes please add me there on PyPI.

**Comment by mauritsvanrees** [comment]
Invitation sent.
